#!/usr/bin/env python3
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PROBE_ROOT = ROOT / "docs" / "control-plane" / "probes"
OUT = ROOT / ".governance" / "control-plane-state" / "first-touch-expected-field-registry.json"
TOOL_SCHEMA_SNAPSHOT = ROOT / ".governance" / "control-plane-state" / "chatgpt-github-tool-schema-snapshot.json"

CANONICAL_CONNECTION_FIELDS = [
    "request.request_id",
    "request.correlation_id",
    "request.trace_id",
    "request.idempotency_key",
    "request.issued_at",
    "request.observed_at",
    "agent.agent_type",
    "agent.agent_name",
    "agent.agent_role",
    "agent.agent_runtime",
    "agent.agent_surface",
    "agent.agent_channel",
    "agent.agent_execution_mode",
    "agent.provider",
    "agent.provider_family",
    "agent.provider_product",
    "agent.provider_ref",
    "agent.public_identity",
    "agent.model",
    "agent.model_family",
    "agent.model_variant",
    "agent.thinking_mode",
    "agent.reasoning_effort",
    "agent.codex_used",
    "agent.codex_workspace_created",
    "agent.codex_task_created",
    "agent.github_app_codex_used",
    "agent.direct_github_functions_used",
    "client.client_instance_id",
    "client.client_type",
    "client.application",
    "client.application_version",
    "client.device_type",
    "client.platform",
    "client.locale",
    "client.language",
    "client.timezone",
    "session.conversation_id",
    "session.conversation_ref",
    "session.conversation_type",
    "session.conversation_start_time",
    "session.first_touch_time",
    "session.session_id",
    "session.session_ref",
    "session.run_id",
    "session.task_id",
    "session.job_id",
    "session.workspace_id",
    "session.workspace_name",
    "session.thread_id",
    "session.turn_id",
    "session.message_id",
    "session.parent_message_id",
    "session.interaction_sequence",
    "session.first_operation",
    "session.last_operation",
    "session.operation_count",
    "session.started_at",
    "session.last_activity_at",
    "session.duration_ms",
    "session.continuity_status",
    "session.new_arrival",
    "session.known_connection",
    "session.resume_detected",
    "session.first_touch_consumed",
    "session.previous_session_ref",
    "session.session_twin_id",
    "session.connection_id",
    "session.first_touch_id",
    "connection.connection_ref",
    "connection.connection_method",
    "connection.surface_class",
    "connection.transport_type",
    "connection.transport_name",
    "connection.transport_layer",
    "connection.transport_surface",
    "connection.connector_name",
    "connection.connector_type",
    "connection.connector_version",
    "connection.api_proxy",
    "connection.direct_connector",
    "connection.github_tool_surface",
    "connection.mcp_transport",
    "connection.http_transport",
    "connection.websocket_transport",
    "connection.oauth_transport",
    "connection.authenticated",
    "connection.actor",
    "connection.provider",
    "connection.capabilities",
    "connection.permissions",
    "connection.scope",
    "connection.endpoint",
    "connection.region",
    "connection.runtime",
    "connection.user_agent",
    "connection.request_metadata",
    "connection.response_metadata",
    "connection.wake_channels",
    "target.repository",
    "target.requested_branch",
    "intent.entry_action",
    "intent.connection_intent",
    "intent.requested_capabilities",
    "control_capabilities.heartbeat",
    "control_capabilities.command_receive",
    "control_capabilities.command_ack",
    "control_capabilities.challenge_response",
    "control_capabilities.checkpoint_report",
    "control_capabilities.progress_report",
    "control_capabilities.context_report",
    "control_capabilities.reobserve_head",
    "github.user_id",
    "github.login",
    "github.name",
    "github.email",
    "github.avatar_url",
    "github.profile_url",
    "github.actor.login",
    "github.actor.id",
    "github.actor.node_id",
    "github.actor.type",
    "github.triggering_actor",
    "github.app_slug",
    "github.app_id",
    "github.installation.id",
    "github.installation.account_login",
    "github.installation.account_id",
    "github.installation.target_type",
    "github.installation.target_id",
    "github.organization",
    "github.organization_id",
    "github.enterprise",
    "github.account_type",
    "github.permission",
    "repository.full_name",
    "repository.id",
    "repository.node_id",
    "repository.name",
    "repository.owner",
    "repository.owner_id",
    "repository.owner_type",
    "repository.visibility",
    "repository.private",
    "repository.archived",
    "repository.fork",
    "repository.default_branch",
    "repository.master_branch",
    "repository.size",
    "repository.clone_url",
    "repository.git_url",
    "repository.html_url",
    "repository.api_url",
    "repository.commits_url",
    "repository.refs_url",
    "repository.created_at",
    "repository.updated_at",
    "repository.pushed_at",
    "repository.language",
    "repository.topics",
    "repository.description",
    "repository.is_template",
    "repository.parent",
    "repository.source",
    "repository.code_search_indexed",
    "permissions.admin",
    "permissions.maintain",
    "permissions.push",
    "permissions.pull",
    "permissions.triage",
    "permissions.contents_read",
    "permissions.contents_write",
    "permissions.issues_read",
    "permissions.issues_write",
    "permissions.pull_requests_read",
    "permissions.pull_requests_write",
    "permissions.actions_read",
    "permissions.actions_write",
    "permissions.metadata_read",
    "permissions.workflows_read",
    "permissions.workflows_write",
    "permissions.checks_read",
    "permissions.checks_write",
    "permissions.statuses_read",
    "permissions.statuses_write",
    "permissions.deployments_read",
    "permissions.deployments_write",
    "permissions.repository_administration",
    "permissions.secrets_read",
    "permissions.secrets_write",
    "permissions.webhooks_read",
    "permissions.webhooks_write",
    "permissions.environments_read",
    "permissions.environments_write",
    "permissions.packages_read",
    "permissions.packages_write",
    "permissions.security_events_read",
    "permissions.security_events_write",
    "permissions.source",
    "permissions.observed_at",
    "git.branch",
    "git.base_branch",
    "git.head_branch",
    "git.ref",
    "git.ref_name",
    "git.ref_type",
    "git.ref_sha",
    "git.head",
    "git.base_sha",
    "git.merge_base_sha",
    "git.default_branch_sha",
    "git.branch_protected",
    "git.branch_protection_enabled",
    "git.branch_required_checks",
    "git.branch_required_reviews",
    "git.branch_push_restrictions",
    "git.branch_force_push_allowed",
    "git.branch_deletion_allowed",
    "git.branch_linear_history_required",
    "commit.sha",
    "commit.parent_sha",
    "commit.parent_shas",
    "commit.tree_sha",
    "commit.message",
    "commit.author_name",
    "commit.author_email",
    "commit.author_date",
    "commit.committer_name",
    "commit.committer_email",
    "commit.committer_date",
    "commit.html_url",
    "commit.api_url",
    "commit.comment_count",
    "commit.signature_verified",
    "commit.signature_reason",
    "commit.verification_status",
    "commit.files_changed",
    "commit.additions",
    "commit.deletions",
    "tree.sha",
    "tree.url",
    "tree.entry_count",
    "tree.paths_observed",
    "tree.files_observed",
    "tree.directories_observed",
    "tree.blob_shas",
    "tree.file_modes",
    "tree.file_types",
    "issue.number",
    "issue.id",
    "issue.node_id",
    "issue.title",
    "issue.state",
    "issue.state_reason",
    "issue.author",
    "issue.assignees",
    "issue.labels",
    "issue.milestone",
    "issue.created_at",
    "issue.updated_at",
    "issue.closed_at",
    "issue.comment_count",
    "issue.locked",
    "issue.html_url",
    "issue.api_url",
    "issue.author_association",
    "pull_request.number",
    "pull_request.id",
    "pull_request.title",
    "pull_request.state",
    "pull_request.draft",
    "pull_request.merged",
    "pull_request.mergeable",
    "pull_request.merge_commit_sha",
    "pull_request.author",
    "pull_request.base_branch",
    "pull_request.base_sha",
    "pull_request.head_branch",
    "pull_request.head_sha",
    "pull_request.head_repo",
    "pull_request.created_at",
    "pull_request.updated_at",
    "pull_request.closed_at",
    "pull_request.merged_at",
    "pull_request.commits",
    "pull_request.changed_files",
    "pull_request.additions",
    "pull_request.deletions",
    "pull_request.requested_reviewers",
    "pull_request.requested_teams",
    "pull_request.reviews",
    "pull_request.review_state",
    "pull_request.labels",
    "pull_request.checks",
    "pull_request.statuses",
    "pull_request.html_url",
    "workflow.workflow_id",
    "workflow.name",
    "workflow.ref",
    "workflow.sha",
    "workflow.run_id",
    "workflow.run_number",
    "workflow.run_attempt",
    "workflow.run_status",
    "workflow.run_conclusion",
    "workflow.event",
    "workflow.actor",
    "workflow.head_sha",
    "workflow.head_branch",
    "workflow.created_at",
    "workflow.updated_at",
    "workflow.job_id",
    "workflow.job_name",
    "workflow.job_status",
    "workflow.job_conclusion",
    "workflow.job_started_at",
    "workflow.job_completed_at",
    "workflow.job_steps",
    "workflow.step_name",
    "workflow.step_status",
    "workflow.step_conclusion",
    "workflow.artifact_id",
    "workflow.artifact_name",
    "workflow.artifact_size",
    "workflow.artifact_created_at",
    "workflow.artifact_expired",
    "workflow.check_suite_id",
    "workflow.check_run_id",
    "workflow.check_status",
    "workflow.check_conclusion",
    "tool.name",
    "tool.namespace",
    "tool.provider",
    "tool.operation",
    "tool.category",
    "tool.call_index",
    "tool.call_timestamp",
    "tool.completion_timestamp",
    "tool.duration_ms",
    "tool.success",
    "tool.error",
    "tool.error_type",
    "tool.error_code",
    "tool.retry_count",
    "tool.retry_reason",
    "tool.request_id",
    "tool.response_id",
    "tool.target_repository",
    "tool.target_branch",
    "tool.target_sha",
    "tool.target_issue",
    "tool.target_pr",
    "tool.search_query",
    "tool.parameters_safe",
    "tool.result_metadata",
    "tool.response_status",
    "sequence.sequence_number",
    "sequence.start",
    "sequence.end",
    "sequence.first_tool_call",
    "sequence.last_tool_call",
    "sequence.previous_tool_call",
    "sequence.next_tool_call",
    "sequence.operation_order",
    "sequence.operation_count",
    "sequence.read_count",
    "sequence.write_count",
    "sequence.search_count",
    "sequence.issue_read_count",
    "sequence.pr_read_count",
    "sequence.commit_read_count",
    "sequence.branch_read_count",
    "sequence.workflow_read_count",
    "sequence.error_count",
    "sequence.retry_count",
    "fingerprint.first_repository_observed",
    "fingerprint.first_branch_observed",
    "fingerprint.first_sha_observed",
    "fingerprint.first_issue_observed",
    "fingerprint.first_pr_observed",
    "fingerprint.first_commit_observed",
    "fingerprint.first_workflow_observed",
    "fingerprint.first_tool_used",
    "fingerprint.first_action_class",
    "fingerprint.first_resource_type",
    "fingerprint.first_resource_ref",
    "fingerprint.first_mutation_attempted",
    "fingerprint.first_mutation_succeeded",
    "fingerprint.first_touch_fingerprint",
    "fingerprint.first_touch_digest",
    "repository_state.observed_head",
    "repository_state.observed_default_branch",
    "repository_state.observed_branch",
    "repository_state.observed_tree",
    "repository_state.observed_parent",
    "repository_state.observed_last_commit_message",
    "repository_state.observed_last_commit_author",
    "repository_state.observed_last_commit_time",
    "repository_state.observed_recent_commits",
    "repository_state.observed_open_pr_count",
    "repository_state.observed_open_issue_count",
    "repository_state.observed_recent_workflows",
    "repository_state.repository_dirty",
    "repository_state.working_tree_clean",
    "repository_state.local_clone_present",
    "repository_state.local_worktree_present",
    "repository_state.local_git_status",
    "repository_state.local_branch",
    "repository_state.local_remote",
    "repository_state.local_upstream",
    "repository_state.local_ahead",
    "repository_state.local_behind",
    "repository_state.local_untracked_files",
    "correlation.event_type",
    "correlation.event_id",
    "correlation.event_timestamp",
    "correlation.actor",
    "correlation.repository",
    "correlation.branch",
    "correlation.sha",
    "correlation.issue",
    "correlation.pr",
    "correlation.confidence",
    "correlation.method",
    "correlation.window_ms",
    "correlation.before_first_touch",
    "correlation.after_first_touch",
    "gscc.identity_id",
    "gscc.identity_anchor",
    "gscc.identity_strength",
    "gscc.identity_status",
    "gscc.first_capture_id",
    "gscc.last_capture_id",
    "gscc.first_observed_at",
    "gscc.last_seen_at",
    "gscc.first_touch_consumed",
    "gscc.continuation_detected",
    "gscc.duplicate_first_touch",
    "gscc.identity_collision",
    "gscc.identity_conflict",
    "gscc.identity_resolution_reason",
    "gse.session_twin_id",
    "gse.identity_id",
    "gse.revision",
    "gse.last_event_type",
    "gse.session_attach",
    "gse.session_resume",
    "gse.updated_at",
    "gse.projected_fields",
    "gse.missing_fields",
    "gse.conflicting_fields",
    "gse.confidence",
    "gse.projection_source",
    "gacr.session_id",
    "gacr.connection_ref",
    "gacr.client_instance_id",
    "gacr.provider",
    "gacr.provider_ref",
    "gacr.agent",
    "gacr.surface_class",
    "gacr.connection_method",
    "gacr.event_type",
    "gacr.attach_status",
    "gacr.resume_status",
    "gacr.claim_id",
    "gacr.beacon_id",
    "gacr.correlation_id",
    "gacr.dispatch_id",
    "gacr.takeover_id",
    "gacr.forensics_ref",
    "gacr.last_seen_at",
    "gacr.continuity_status",
    "gacr.connection_fingerprint",
    "gacr.connection_envelope_digest",
    "gacr.context_digest",
    "gacr.dedupe_key",
    "gacr.session_status",
    "gacr.connected_at",
    "gacr.lease_expires_at",
    "gacr.provider_conversation_ref",
    "gacr.provider_conversation_url",
    "gate.gate_id",
    "gate.gate_name",
    "gate.gate_owner",
    "gate.gate_phase",
    "gate.gate_status",
    "gate.gate_entry_time",
    "gate.gate_exit_time",
    "gate.gate_required_blocks",
    "gate.gate_satisfied_blocks",
    "gate.gate_missing_blocks",
    "gate.gate_failure_reason",
    "gate.gate_block_reason",
    "gate.gate_unlock_effect",
    "gate.gate_authority_effect",
    "gate.detected",
    "gate.captured",
    "gate.normalized",
    "gate.identified",
    "gate.correlated",
    "gate.admitted",
    "gate.preauthorized",
    "gate.qualified",
    "gate.enriched",
    "gate.attached",
    "gate.resumed",
    "gate.blocked",
    "gate.refused",
    "gate.incomplete",
    "gate.ready_for_q1",
    "gate.ready_for_governed_entry",
    "provenance.value",
    "provenance.source",
    "provenance.source_type",
    "provenance.source_component",
    "provenance.source_tool",
    "provenance.source_api",
    "provenance.source_ref",
    "provenance.source_sha",
    "provenance.source_event",
    "provenance.source_timestamp",
    "provenance.observed_at",
    "provenance.ingested_at",
    "provenance.normalized_at",
    "provenance.derived_at",
    "provenance.provenance_status",
    "provenance.evidence_ref",
    "quality.confidence",
    "quality.confidence_score",
    "quality.evidence_strength",
    "quality.identity_strength",
    "quality.source_reliability",
    "quality.verification_status",
    "quality.verified",
    "quality.corroborated",
    "quality.conflicting",
    "quality.stale",
    "quality.partial",
    "quality.complete",
    "timestamps.observed_at",
    "timestamps.provider_observed_at",
    "timestamps.tool_called_at",
    "timestamps.tool_completed_at",
    "timestamps.ingested_at",
    "timestamps.normalized_at",
    "timestamps.persisted_at",
    "timestamps.gscc_processed_at",
    "timestamps.gse_projected_at",
    "timestamps.gacr_attached_at",
    "timestamps.gate_evaluated_at",
    "timestamps.last_seen_at",
    "timestamps.first_seen_at",
    "timestamps.created_at",
    "timestamps.updated_at",
    "versions.capture_schema_version",
    "versions.provider_envelope_version",
    "versions.gscc_version",
    "versions.gse_version",
    "versions.gacr_version",
    "versions.first_touch_collector_version",
    "versions.field_registry_version",
    "versions.gate_catalog_version",
    "versions.workflow_version",
    "versions.repository_governance_version",
    "versions.template_version",
    "versions.client_version",
    "versions.connector_version",
    "versions.runtime_version",
    "versions.application_version",
    "environment.runtime_os",
    "environment.runtime_arch",
    "environment.runtime_name",
    "environment.runtime_environment",
    "environment.runner_os",
    "environment.runner_arch",
    "environment.runner_name",
    "environment.runner_environment",
    "environment.python_version",
    "environment.node_version",
    "environment.shell",
    "environment.workspace_path",
    "environment.temp_path",
    "environment.tool_cache_path",
    "environment.ci",
    "environment.locale",
    "environment.language",
    "environment.timezone",
    "environment.region",
    "environment.cloud_provider",
    "environment.device_type",
    "environment.platform",
    "environment.application_client",
    "environment.application_client_version",
    "result.http_status",
    "result.api_status",
    "result.success",
    "result.failure",
    "result.error_type",
    "result.error_code",
    "result.error_message_safe",
    "result.rate_limit_remaining",
    "result.rate_limit_reset",
    "result.retry_after",
    "result.redirect_count",
    "result.response_size",
    "result.response_content_type",
    "result.response_metadata",
    "result.response_object_type",
    "result.response_count",
    "negative.codex_used",
    "negative.github_app_codex_used",
    "negative.codex_workspace_created",
    "negative.codex_task_created",
    "negative.manual_issue_created",
    "negative.manual_comment_created",
    "negative.manual_dispatch_created",
    "negative.branch_created",
    "negative.commit_created",
    "negative.pr_created",
    "negative.repository_mutated",
    "negative.secret_accessed",
    "negative.token_exposed",
    "negative.oauth_secret_exposed",
    "negative.private_key_exposed",
    "negative.conversation_id_exposed",
    "negative.session_id_exposed",
    "negative.installation_id_exposed",
    "negative.client_id_exposed",
    "negative.ip_exposed",
    "negative.local_clone_present",
    "negative.worktree_present",
    "security.sensitive_value_present",
    "security.redacted",
    "security.value_length",
    "security.source",
    "security.reason",
    "task.task_id",
    "claim.claim_id",
    "checkpoint.ref",
]

STATUS_VALUES = [
    "OBSERVED","DERIVED","UNAVAILABLE","UNKNOWN","NOT_EXPOSED","REDACTED","DENIED","STALE","NOT_APPLICABLE"
]

def norm_key(value: str) -> str:
    value = value.strip().strip(chr(96))
    value = re.sub(r"[^A-Za-z0-9_.:/-]+", "_", value)
    return value.strip("_").lower()

def parse_probe(path: Path):
    lines = path.read_text(encoding="utf-8").splitlines()
    observations = []
    in_code = False
    raw = False
    buf = []
    section = ""
    for idx, line in enumerate(lines, start=1):
        h = re.match(r"^##\s+(?:(?:\d+)\.\s+)?(.+?)\s*$", line)
        if h and not in_code:
            section = h.group(1).strip()
            raw = section.lower() in {"raw inventory","raw anchor inventory"}
            continue
        if line.strip().startswith(chr(96) * 3):
            if in_code and raw:
                vals=[(n,t.strip()) for n,t in buf if t.strip()]
                for j in range(0,len(vals)-1,2):
                    observations.append((vals[j][1], vals[j+1][1], vals[j+1][0], section, "RAW_INVENTORY"))
                buf=[]
            in_code=not in_code
            continue
        if in_code:
            if raw: buf.append((idx,line))
            continue
        m=re.match(r"^[-*>]\s*([^:]+):\s*(.*?)\s*$", line)
        if m:
            observations.append((m.group(1),m.group(2),idx,section,"KEY_VALUE"))
            continue
        m=re.match(r"^([A-Za-z0-9_ /()#.+-]+):\s*$",line)
        if m:
            j=idx
            while j < len(lines) and not lines[j].strip():
                j+=1
            if j < len(lines):
                nxt=lines[j].strip()
                if nxt.startswith(chr(96)) and nxt.endswith(chr(96)):
                    observations.append((m.group(1),nxt,j+1,section,"LABEL_VALUE"))
    return observations

def main():
    fields={}
    probe_paths=sorted(PROBE_ROOT.glob("*.md"))
    parsed_probes={p: parse_probe(p) for p in probe_paths}
    tool_rows=[]
    if TOOL_SCHEMA_SNAPSHOT.exists():
        tool_rows=json.loads(TOOL_SCHEMA_SNAPSHOT.read_text(encoding="utf-8")).get("fields", [])

    for p in probe_paths:
        for key,value,line,section,kind in parsed_probes[p]:
            nk=norm_key(key)
            if not nk: continue
            item=fields.setdefault(nk,{
                "field_id":nk,
                "aliases":[],
                "sources":[],
                "expected_status_contract":STATUS_VALUES,
            })
            if key not in item["aliases"]: item["aliases"].append(key)
            item["sources"].append({
                "source_path":str(p.relative_to(ROOT)),
                "source_line":line,
                "section":section,
                "source_kind":kind,
            })
    if tool_rows:
        for row in tool_rows:
            key = str(row.get("field_id") or "")
            nk = norm_key(key)
            if not nk:
                continue
            item = fields.setdefault(nk, {
                "field_id": nk,
                "aliases": [],
                "sources": [],
                "expected_status_contract": STATUS_VALUES,
            })
            if key not in item["aliases"]:
                item["aliases"].append(key)
            item["sources"].append({
                "source_path": str(TOOL_SCHEMA_SNAPSHOT.relative_to(ROOT)),
                "source_line": None,
                "section": "github_tool_schema",
                "source_kind": "TOOL_SCHEMA",
            })

    for key in CANONICAL_CONNECTION_FIELDS:
        nk=norm_key(key)
        item=fields.setdefault(nk,{
            "field_id":nk,
            "aliases":[],
            "sources":[],
            "expected_status_contract":STATUS_VALUES,
        })
        if key not in item["aliases"]: item["aliases"].append(key)
        item["sources"].append({"source_path":"CANONICAL_CONNECTION_FIELDS","source_line":None,"section":"connection","source_kind":"CANONICAL"})
    out={
        "schema":"first-touch-expected-field-registry/v1",
        "purpose":"Every expected first-touch/connection field must have a value or an explicit non-value status; silent absence is not complete.",
        "source_probe_files":[str(p.relative_to(ROOT)) for p in probe_paths],
        "status_values":STATUS_VALUES,
        "probe_observation_count": sum(len(parsed_probes[p]) for p in probe_paths),
        "tool_schema_field_count": len(tool_rows),
        "field_count":len(fields),
        "fields":[fields[k] for k in sorted(fields)],
        "expected_observations": (
            [
                {
                    "observation_id": f"probe:{str(p.relative_to(ROOT))}:{line}:{norm_key(key)}",
                    "field_id": norm_key(key),
                    "source_kind": "PROBE_REFERENCE",
                    "source_path": str(p.relative_to(ROOT)),
                    "source_line": line,
                }
                for p in probe_paths
                for key, value, line, section, kind in parsed_probes[p]
                if norm_key(key)
            ]
            + [
                {
                    "observation_id": f"github_tool:{row.get('tool')}:{row.get('field')}",
                    "field_id": norm_key(str(row.get("field_id") or "")),
                    "source_kind": "TOOL_SCHEMA",
                    "source_path": str(TOOL_SCHEMA_SNAPSHOT.relative_to(ROOT)),
                    "source_line": None,
                }
                for row in tool_rows
                if norm_key(str(row.get("field_id") or ""))
            ]
            + [
                {
                    "observation_id": f"canonical:{norm_key(key)}",
                    "field_id": norm_key(key),
                    "source_kind": "CANONICAL_CONNECTION_FIELD",
                    "source_path": "CANONICAL_CONNECTION_FIELDS",
                    "source_line": None,
                }
                for key in CANONICAL_CONNECTION_FIELDS
            ]
        ),
        "authority_granted":False,
    }
    out["expected_observation_count"] = len(out["expected_observations"])
    OUT.write_text(json.dumps(out,indent=2,ensure_ascii=False,sort_keys=True)+"\n",encoding="utf-8")
    print(json.dumps({"status":"EXPECTED_FIELD_REGISTRY_BUILT","field_count":len(fields),"expected_observation_count":out["expected_observation_count"],"output":str(OUT)},indent=2))

if __name__=="__main__":
    main()
